policies:
  - name: r-security-group-ingress-all-tcp-access-replace-vpn-ip
    resource: security-group
    description: "Account {account_id} - VPC security groups should restrict ingress TCP access from 0.0.0.0/0 replace with VPN IP"
    filters:
      - or:
        - type: ingress
          IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          Cidr:
            value: "0.0.0.0/0"
        - type: ingress
          IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrV6:
            value: "::/0"
    actions:
      - type: set-permissions
        remove-ingress: matched
        add-ingress:
          - IpPermissions:
              - IpProtocol: TCP
                FromPort: 0
                ToPort: 65535
                IpRanges:
                  - Description: "VPN IP"
                    CidrIp: "1.2.3.4/32"
      - type: webhook
        url: REPLACE_WEBHOOK_HERE
        body: |-
          {
            "attachments": [
              {
                "fallback": `CloudCustodian Policy Violation`,
                "title": policy.description,
                "color": `danger`,
                "fields": [
                  {
                    "title": `Priority`,
                    "value": `medium`,
                    "short": `true`
                  },
                  {
                    "title": `AutoTag_Creator`,
                    "value": resource.Tags[?Key==`AutoTag_Creator`].Value | [0] || `Tag Unavailable`,
                    "short": `true`
                  },
                  {
                    "title": `Default Security Group ID`,
                    "value": resource.GroupId,
                    "short": `true`
                  },
                  {
                    "title": `Region`,
                    "value": region,
                    "short": `true`
                  },
                  {
                    "title": `Resource Link`,
                    "value": join('', [`https://console.aws.amazon.com/ec2/v2/home?region=`, region, `#SecurityGroup:groupId=`, resource.GroupId]),
                    "short": `false`
                  }
                ],
                "footer": `Powered By CldCvr DevSecOps`,
                "footer_icon": `https://a.cldcvr.com/cldcvr/favicons/64px.png`
              }
            ]
          }
